### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by gbbr** [sstur/draft-js-import-html#15]
README says:

```
This project is still under development. If you want to help out, please open an issue to discuss or join us on Slack.
```

But no indication whatsoever about how to obtain an account...

**Comment by leniartek** [comment]
Visit the page [https://draftjs.herokuapp.com/](https://draftjs.herokuapp.com/) and add your email address to obtain invitation to the slack group.

**Comment by gbbr** [comment]
Thanks for the reply, but in 3 months since I wrote this I have already written my own import/export.
