### ISSUE TITLE
Make this util isomorpic

### ISSUE THREAD

**Issue by indianscout** [sstur/draft-js-import-html#2]
Would be nice if this util is isomorphic. The following works for me server side (lib/parseHTML.js)

``` javascript
'use strict';
var DOMParser = require('xmldom').DOMParser;

Object.defineProperty(exports, "__esModule", {
  value: true
});

function parseHTML(html) {
  var parser = new DOMParser();
  var doc = parser.parseFromString(html, 'text/html');
  return doc.documentElement;
}

exports.default = parseHTML;
```

An isomorphic approach is useful, when migrating/converting legacy html content to Draftjs.
This would allow me to migrate content with migration scripts on the server.

**Comment by SumeetR** [comment]
I agree with @indianscout, making this package isomorphic would increase its compatibility, and hence its value, with many React projects out there. I've tried the suggested code and it works great, maybe @sstur could let @indianscout make a PR?

Cheers,
S.

**Comment by sstur** [comment]
Thanks @indianscout! I'm totally open to this, but:
- It should be a peer or optional dependency somehow so we don't include the parsing code in people's front-end build. I'm open to ideas about how to do that.
- I already use jsdom in my tests, I'd like to use the HTML parser from that if possible because it's extremely well tested to behave like the browser's parser.

I'm open to a PR for this or even just suggestions for point 1 and I can get to it.

Thanks!

**Comment by indianscout** [comment]
The easiest way to achieve 1) is to move the parseHtml outside of the module and leave it up to the user what kind of parser has to be used. 
The only necessary thing is to handover a W3C compliant DOM node to stateFromHTML():

``` javascript
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = stateFromHTML;

var _draftJsImportElement = require('draft-js-import-element');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function stateFromHTML(element) {
  return (0, _draftJsImportElement.stateFromElement)(element);
}
```

(Not tested yet)

This would also solve 2) because the user can choose what kind of XML parser has to be used.

**Comment by sstur** [comment]
Thanks @indianscout. I've done it according to your suggestion (letting the user provide her own parser implementation).

Now `stateFromHTML` can take a second "options" parameter which can have a "parser" property to use whatever parser you like. The parser will receive one argument (html: string) and it must return an Element object which behaves like a DOM Element, or minimally, like a [synthetic-dom](https://www.npmjs.com/package/synthetic-dom) element.

This was a pretty easy feature to add so thanks for the suggestion!
